from pydantic import BaseModel, Field
from typing import List


class SummarizeNewsArticlesOutput(BaseModel):
    """Pydantic model for summarize_news_articles node outputs."""
    summary_count: int = (
        Field(..., description="Number of article summaries generated")
    )
    summaries: List[str] = (
        Field(..., description="Concise summaries for each news article, ordered as input")
    )


class AnalyzeSentimentOutput(BaseModel):
    """Pydantic model for analyze_sentiment node outputs."""
    article_index: List[int] = (
        Field(..., description="The sequential index of each article in the input list.")
    )
    sentiment_category: List[str] = (
        Field(..., description="Sentiment category for each article, one of 'positive', 'negative', or 'neutral'.")
    )
    sentiment_confidence: List[float] = (
        Field(..., description="Confidence score (0.0 to 1.0) for the assigned sentiment.")
    )


def analyze_sentiment(summarize_news_articles_input: SummarizeNewsArticlesOutput, **kwargs) -> AnalyzeSentimentOutput:
    """
    Analyze the sentiment of news article summaries.

    Parameters
    ----------
    summaries : List[str]
        A list of concise summaries generated by `summarize_news_articles`.

    Returns
    -------
    dict
        A dictionary with keys `article_index`, `sentiment_category`, and
        `sentiment_confidence`, each mapping to a list of the same length as
        the input `summaries`.

    Raises
    ------
    ValueError
        Raised if `summaries` is empty or contains non-string entries.

    Examples
    --------
    >>> results = analyze_sentiment(['Neutral news about weather'])
    {'article_index': [0], 'sentiment_category': ['neutral'],
    'sentiment_confidence': [0.65]}

    """
    return AnalyzeSentimentOutput(
        article_index=[],
        sentiment_category=[],
        sentiment_confidence=[],
    )