from pydantic import BaseModel, Field
from typing import List


class DecomposeObjectiveIntoTasksOutput(BaseModel):
    """Pydantic model for decompose_objective_into_tasks node outputs."""
    tasks: List[str] = (
        Field(..., description="List of task descriptions that represent the decomposed workflow objective")
    )
    task_count: int = (
        Field(..., description="Number of tasks identified in the decomposition")
    )


class IdentifyTaskDependenciesOutput(BaseModel):
    """Pydantic model for identify_task_dependencies node outputs."""
    tasks: List[str] = Field(..., description="List of identified task names.")
    dependencies: List[str] = (
        Field(..., description="List of dependency relationships in the format 'TaskA depends on TaskB'.")
    )
    dependency_exists: bool = (
        Field(..., description="Indicates whether any dependencies were identified.")
    )


def identify_task_dependencies(decompose_objective_into_tasks_input: DecomposeObjectiveIntoTasksOutput, **kwargs) -> IdentifyTaskDependenciesOutput:
    """
    Infers direct dependencies between tasks from a list of task descriptions.

    Parameters
    ----------
    tasks : List[str]
        Task descriptions generated by decompose_objective_into_tasks.

    Returns
    -------
    Dict[str, Any]
        A dictionary with keys 'tasks', 'dependencies', and
        'dependency_exists' matching the node's output structure.

    Raises
    ------
    ValueError
        If the input `tasks` is not a list of strings or is empty.

    Examples
    --------
    >>> tasks_input = ["Collect data", "Preprocess data", "Train model",
    "Evaluate model"]
    >>> # Assuming the following simple dependency logic:
    >>> # 'Preprocess data' depends on 'Collect data'
    >>> # 'Train model' depends on 'Preprocess data'
    >>> # 'Evaluate model' depends on 'Train model'
    >>> result = identify_task_dependencies(tasks_input)
    >>> print(result)
    {'tasks': ['Collect data', 'Preprocess data', 'Train model', 'Evaluate
    model'], 'dependencies': ['Preprocess data depends on Collect data', 'Train
    model depends on Preprocess data', 'Evaluate model depends on Train model'],
    'dependency_exists': True}

    >>> tasks_input = ["Generate report", "Publish report"]
    >>> # No explicit dependencies specified
    >>> result = identify_task_dependencies(tasks_input)
    >>> print(result)
    {'tasks': ['Generate report', 'Publish report'], 'dependencies': [],
    'dependency_exists': False}

    """
    return IdentifyTaskDependenciesOutput(
        tasks=[],
        dependencies=[],
        dependency_exists=False,
    )