from ._identify_task_dependencies.validate_tasks_input import validate_tasks_input
from ._identify_task_dependencies.analyze_task_dependencies import analyze_task_dependencies
from ._identify_task_dependencies.format_dependencies import format_dependencies
from ._identify_task_dependencies.check_dependencies_exist import check_dependencies_exist

from pydantic import BaseModel, Field
from typing import List


class DecomposeObjectiveIntoTasksOutput(BaseModel):
    """Pydantic model for decompose_objective_into_tasks node outputs."""
    tasks: List[str] = (
        Field(..., description = (
            "List of task descriptions that represent the decomposed workflow objective")
        )
    )
    task_count: int = (
        Field(..., description = (
            "Number of tasks identified in the decomposition")
        )
    )


class IdentifyTaskDependenciesOutput(BaseModel):
    """Pydantic model for identify_task_dependencies node outputs."""
    tasks: List[str] = Field(..., description="List of identified task names.")
    dependencies: List[str] = (
        Field(..., description = (
            "List of dependency relationships in the format 'TaskA depends on TaskB'.")
        )
    )
    dependency_exists: bool = (
        Field(..., description = (
            "Indicates whether any dependencies were identified.")
        )
    )


def identify_task_dependencies(decompose_objective_into_tasks_input: DecomposeObjectiveIntoTasksOutput, **kwargs) -> IdentifyTaskDependenciesOutput:
    """
    Infers direct dependencies between tasks from a list of task descriptions.

    Parameters
    ----------
    tasks : List[str]
        Task descriptions generated by decompose_objective_into_tasks.

    Returns
    -------
    Dict[str, Any]
        A dictionary with keys 'tasks', 'dependencies', and
        'dependency_exists' matching the node's output structure.

    Raises
    ------
    ValueError
        If the input `tasks` is not a list of strings or is empty.

    Examples
    --------
    >>> tasks_input = ["Collect data", "Preprocess data", "Train model",
    "Evaluate model"]
    >>> # Assuming the following simple dependency logic:
    >>> # 'Preprocess data' depends on 'Collect data'
    >>> # 'Train model' depends on 'Preprocess data'
    >>> # 'Evaluate model' depends on 'Train model'
    >>> result = identify_task_dependencies(tasks_input)
    >>> print(result)
    {'tasks': ['Collect data', 'Preprocess data', 'Train model', 'Evaluate
    model'], 'dependencies': ['Preprocess data depends on Collect data', 'Train
    model depends on Preprocess data', 'Evaluate model depends on Train model'],
    'dependency_exists': True}

    >>> tasks_input = ["Generate report", "Publish report"]
    >>> # No explicit dependencies specified
    >>> result = identify_task_dependencies(tasks_input)
    >>> print(result)
    {'tasks': ['Generate report', 'Publish report'], 'dependencies': [],
    'dependency_exists': False}

    """
    tasks: List[str] = decompose_objective_into_tasks_input.tasks
    
    validated_tasks: List[str] = validate_tasks_input(tasks=tasks)
    
    dependency_pairs: List[tuple] = analyze_task_dependencies(tasks=validated_tasks)
    
    dependency_strings: List[str] = format_dependencies(dependency_pairs=dependency_pairs)
    
    has_dependencies: bool = check_dependencies_exist(dependencies=dependency_strings)
    
    return IdentifyTaskDependenciesOutput(
        tasks=validated_tasks,
        dependencies=dependency_strings,
        dependency_exists=has_dependencies
    )