from ._execute_trades.validate_trading_signals import validate_trading_signals
from ._execute_trades.send_order_to_exchange import send_order_to_exchange
from ._execute_trades.process_order_result import process_order_result

from pydantic import BaseModel, Field
from typing import List


class GenerateTradingSignalsOutput(BaseModel):
    """Pydantic model for generate_trading_signals node outputs."""
    trading_signals: List[str] = (
        Field(..., description="List of trading signals")
    )


class ExecuteTradesOutput(BaseModel):
    """Pydantic model for execute_trades node outputs."""
    trade_outcomes: List[str] = Field(..., description="List of trade outcomes")


def execute_trades(generate_trading_signals_input: GenerateTradingSignalsOutput, **kwargs) -> ExecuteTradesOutput:
    """
    Execute trades based on generated trading signals.

    Parameters
    ----------
    trading_signals : List[str]
        List of trading signals generated by the generate_trading_signals
        node.

    Returns
    -------
    List[str]
        List of trade outcomes resulting from the executed trades.

    Raises
    ------
    ValueError
        If the input trading_signals list is empty or contains invalid
        signals.
    ConnectionError
        If there's a failure in sending orders to the exchange or broker.

    Examples
    --------
    >>> execute_trades(trading_signals=['buy', 'sell', 'hold'])
    ['success', 'success', 'skipped']

    >>> execute_trades(trading_signals=['buy', 'invalid_signal'])
    ['success', 'failed']

    """
    trading_signals: List[str] = generate_trading_signals_input.trading_signals
    
    validated_signals: List[str] = validate_trading_signals(signals=trading_signals)
    
    trade_outcomes: List[str] = []
    
    for signal in validated_signals:
        if signal == 'hold':
            outcome: str = 'skipped'
        else:
            order_result: dict = send_order_to_exchange(signal=signal)
            outcome: str = process_order_result(result=order_result)
        
        trade_outcomes.append(outcome)
    
    return ExecuteTradesOutput(trade_outcomes=trade_outcomes)