from ._execute_trades.validate_signal_inputs import validate_signal_inputs
from ._execute_trades.generate_trade_id import generate_trade_id
from ._execute_trades.execute_single_trade import execute_single_trade

from pydantic import BaseModel, Field
from typing import List


class GenerateTradeSignalsOutput(BaseModel):
    """Pydantic model for generate_trade_signals node outputs."""
    trade_signals: List[str] = (
        Field(..., description="List of trade signals (buy, sell, hold)")
    )
    signal_confidences: List[float] = (
        Field(..., description="List of signal confidences")
    )


class ExecuteTradesOutput(BaseModel):
    """Pydantic model for execute_trades node outputs."""
    trade_outcomes: List[str] = (
        Field(..., description="List of trade outcomes (success, failure)")
    )
    trade_ids: List[str] = Field(..., description="List of trade IDs")


def execute_trades(generate_trade_signals_input: GenerateTradeSignalsOutput, **kwargs) -> ExecuteTradesOutput:
    """
    Execute trades based on generated trade signals and return the outcomes and
    trade IDs.

    Parameters
    ----------
    trade_signals : List[str]
        List of trade signals (buy, sell, hold) generated by the
        generate_trade_signals node.
    signal_confidences : List[float]
        List of signal confidences corresponding to the trade signals.

    Returns
    -------
    Tuple[List[str], List[str]]
        A tuple containing a list of trade outcomes (success, failure) and a
        list of trade IDs.

    Raises
    ------
    ValueError
        If the lengths of trade_signals and signal_confidences do not match.
    RuntimeError
        If trade execution fails due to external factors.

    Examples
    --------
    >>> trade_signals = ['buy', 'sell', 'hold']
    >>> signal_confidences = [0.8, 0.9, 0.7]
    >>> trade_outcomes, trade_ids = execute_trades(trade_signals,
    signal_confidences)
    (['success', 'success', 'failure'], ['trade123', 'trade456', 'trade789'])

    >>> trade_signals = ['buy', 'sell']
    >>> signal_confidences = [0.85, 0.95]
    >>> trade_outcomes, trade_ids = execute_trades(trade_signals,
    signal_confidences)
    (['success', 'success'], ['trade101', 'trade102'])

    """
    trade_signals = generate_trade_signals_input.trade_signals
    signal_confidences = generate_trade_signals_input.signal_confidences
    
    validate_signal_inputs(signals=trade_signals, confidences=signal_confidences)
    
    trade_outcomes: List[str] = []
    trade_ids: List[str] = []
    
    for signal, confidence in zip(trade_signals, signal_confidences):
        trade_id: str = generate_trade_id()
        execution_result: str = execute_single_trade(signal=signal, confidence=confidence, trade_id=trade_id)
        trade_outcomes.append(execution_result)
        trade_ids.append(trade_id)
    
    return ExecuteTradesOutput(
        trade_outcomes=trade_outcomes,
        trade_ids=trade_ids,
    )