from ._execute_trades.validate_input_signals import validate_input_signals
from ._execute_trades.process_hold_signal import process_hold_signal
from ._execute_trades.generate_hold_details import generate_hold_details
from ._execute_trades.execute_trade_order import execute_trade_order
from ._execute_trades.extract_trade_outcome import extract_trade_outcome
from ._execute_trades.extract_trade_details import extract_trade_details

from pydantic import BaseModel, Field
from typing import List


class GenerateTradingSignalsOutput(BaseModel):
    """Pydantic model for generate_trading_signals node outputs."""
    trading_signals: List[str] = (
        Field(..., description="List of trading signals (buy/sell/hold).")
    )
    signal_confidence: List[float] = (
        Field(..., description="List of confidence levels for each trading signal.")
    )


class ExecuteTradesOutput(BaseModel):
    """Pydantic model for execute_trades node outputs."""
    trade_outcomes: List[str] = (
        Field(..., description="List of outcomes for each trade executed.")
    )
    trade_details: List[str] = (
        Field(..., description="List of details for each trade executed.")
    )


def execute_trades(generate_trading_signals_input: GenerateTradingSignalsOutput, **kwargs) -> ExecuteTradesOutput:
    """
    Executes trades based on the provided trading signals and confidence levels.

    Parameters
    ----------
    trading_signals : List[str]
        List of trading signals (buy/sell/hold) generated by the
        `generate_trading_signals` node.
    signal_confidence : List[float]
        List of confidence levels for each trading signal.

    Returns
    -------
    Tuple[List[str], List[str]]
        A tuple containing two lists: `trade_outcomes` and `trade_details`.
        `trade_outcomes` is a list of outcomes for each trade executed, and
        `trade_details` is a list of details for each trade executed.

    Raises
    ------
    ValueError
        If the lengths of `trading_signals` and `signal_confidence` do not
        match.
    TypeError
        If `trading_signals` is not a list of strings or `signal_confidence`
        is not a list of floats.

    Examples
    --------
    >>> trading_signals = ['buy', 'sell', 'hold']
    >>> signal_confidence = [0.8, 0.7, 0.9]
    >>> trade_outcomes, trade_details = execute_trades(trading_signals,
    signal_confidence)
    trade_outcomes = ['success', 'success', 'held']
    trade_details = ['Bought 100 units', 'Sold 50 units', 'Held 200 units']

    >>> trading_signals = ['buy', 'sell']
    >>> signal_confidence = [0.85, 0.75]
    >>> trade_outcomes, trade_details = execute_trades(trading_signals,
    signal_confidence)
    trade_outcomes = ['success', 'failed']
    trade_details = ['Bought 150 units', 'Failed to sell 75 units']

    """
    trading_signals: List[str] = generate_trading_signals_input.trading_signals
    signal_confidence: List[float] = generate_trading_signals_input.signal_confidence
    
    validate_input_signals(signals=trading_signals, confidence=signal_confidence)
    
    trade_outcomes: List[str] = []
    trade_details: List[str] = []
    
    for i, signal in enumerate(trading_signals):
        confidence: float = signal_confidence[i]
        
        if signal.lower() == 'hold':
            outcome: str = process_hold_signal(confidence=confidence)
            detail: str = generate_hold_details(confidence=confidence)
        else:
            trade_execution_result: dict = execute_trade_order(signal=signal, confidence=confidence)
            outcome: str = extract_trade_outcome(result=trade_execution_result)
            detail: str = extract_trade_details(result=trade_execution_result, signal=signal)
        
        trade_outcomes.append(outcome)
        trade_details.append(detail)
    
    return ExecuteTradesOutput(
        trade_outcomes=trade_outcomes,
        trade_details=trade_details,
    )