from ._purchase_ingredients.validate_shopping_list import validate_shopping_list
from ._purchase_ingredients.handle_empty_shopping_list import handle_empty_shopping_list
from ._purchase_ingredients.check_ingredient_availability import check_ingredient_availability
from ._purchase_ingredients.execute_purchase import execute_purchase
from ._purchase_ingredients.verify_purchase_completion import verify_purchase_completion

from pydantic import BaseModel, Field
from typing import List


class CreateShoppingListOutput(BaseModel):
    """Pydantic model for create_shopping_list node outputs."""
    shopping_list: List[str] = (
        Field(..., description="List of ingredients to purchase")
    )


class PurchaseIngredientsOutput(BaseModel):
    """Pydantic model for purchase_ingredients node outputs."""
    purchased_ingredients: List[str] = (
        Field(..., description="List of ingredients purchased")
    )


def purchase_ingredients(create_shopping_list_input: CreateShoppingListOutput, **kwargs) -> PurchaseIngredientsOutput:
    """
    Purchase ingredients based on the shopping list.

    Parameters
    ----------
    shopping_list : List[str]
        List of ingredients to purchase, generated by the
        'create_shopping_list' node.

    Returns
    -------
    List[str]
        List of ingredients that were purchased.

    Raises
    ------
    ValueError
        If the shopping list is empty or contains invalid ingredients.

    Examples
    --------
    >>> shopping_list = ['eggs', 'flour', 'sugar']
    >>> purchased_ingredients = purchase_ingredients(shopping_list)
    ['eggs', 'flour', 'sugar']

    >>> shopping_list = []
    >>> purchased_ingredients = purchase_ingredients(shopping_list)
    []

    """
    shopping_list: List[str] = create_shopping_list_input.shopping_list
    
    validated_list: List[str] = validate_shopping_list(shopping_list=shopping_list)
    
    if not validated_list:
        handle_empty_shopping_list()
    
    available_ingredients: List[str] = check_ingredient_availability(ingredients=validated_list)
    
    purchased_items: List[str] = execute_purchase(ingredients=available_ingredients)
    
    final_purchased_list: List[str] = verify_purchase_completion(purchased_items=purchased_items)
    
    return PurchaseIngredientsOutput(purchased_ingredients=final_purchased_list)