from typing import Dict, Any, List, Optional
from crewai import Agent, Task, Crew
from crewai.project import CrewBase, agent, crew, task
from .models import identify_task_dependencies_output

@CrewBase
class identify_task_dependencies_crew:
    """Crew for identify_task_dependencies operations."""

    @agent
    def identify_task_dependencies_agent(self):
        return Agent(
            role="Identify Task Dependencies Specialist",
            goal="""Identify dependencies between tasks""",
            backstory="""This node processes a list of task descriptions produced by
                         the decomposition step and infers direct dependencies
                         between tasks. It returns the original list of tasks, a
                         concise list of dependency strings, and a flag
                         indicating whether any dependencies exist.""",
            verbose=True
        )


    @task
    def identify_task_dependencies_task(self):
        """Task for identify_task_dependencies."""
        agent = self.identify_task_dependencies_agent()
        return Task(
            description="""Simulate the Python function
                           `identify_task_dependencies`.
                       
                       Function specification:
                       Infers direct dependencies between tasks from a list of
                           task descriptions.
                       
                       Parameters
                       ----------
                       tasks : List[str]
                           Task descriptions generated by
                           decompose_objective_into_tasks.
                       
                       Returns
                       -------
                       Dict[str, Any]
                           A dictionary with keys 'tasks', 'dependencies', and
                           'dependency_exists' matching the node's output
                           structure.
                       
                       Raises
                       ------
                       ValueError
                           If the input `tasks` is not a list of strings or is
                           empty.
                       
                       Examples
                       --------
                       >>> tasks_input = ["Collect data", "Preprocess data",
                           "Train model", "Evaluate model"]
                       >>> # Assuming the following simple dependency logic:
                       >>> # 'Preprocess data' depends on 'Collect data'
                       >>> # 'Train model' depends on 'Preprocess data'
                       >>> # 'Evaluate model' depends on 'Train model'
                       >>> result = identify_task_dependencies(tasks_input)
                       >>> print(result)
                       {'tasks': ['Collect data', 'Preprocess data', 'Train
                           model', 'Evaluate model'], 'dependencies':
                           ['Preprocess data depends on Collect data', 'Train
                           model depends on Preprocess data', 'Evaluate model
                           depends on Train model'], 'dependency_exists': True}
                       
                       >>> tasks_input = ["Generate report", "Publish report"]
                       >>> # No explicit dependencies specified
                       >>> result = identify_task_dependencies(tasks_input)
                       >>> print(result)
                       {'tasks': ['Generate report', 'Publish report'],
                           'dependencies': [], 'dependency_exists': False}
                       
                       Using the provided inputs: Using
                           {decompose_objective_into_tasks_output}, Identify
                           dependencies between tasks""",
            agent=agent,
            expected_output="""{
                               tasks: list of strs  # List of identified task
                               names.
                               dependencies: list of strs  # List of dependency
                               relationships in the format 'TaskA depends on
                               TaskB'.
                               dependency_exists: bool  # Indicates whether any
                               dependencies were identified.
                           }""",
            output_pydantic=identify_task_dependencies_output
        )


    @crew
    # @traceable
    def crew(self):
        """Create the crew instance."""
        return Crew(
            agents=[self.identify_task_dependencies_agent()],
            tasks=[self.identify_task_dependencies_task()],
            verbose=True
        )
